apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-resources-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubernautics  
roleRef:
  kind: ClusterRole
  name: list-resources
  apiGroup: rbac.authorization.k8s.io
