apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernautics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernautics
  template:
    metadata:
      labels:
        app: kubernautics
    spec:
      containers:
        - name: kubernautics
          image: kubernautics:latest
          resources:
            limits:
              memory: '1024Mi'
              cpu: '1000m'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernautics-service
spec:
  type: NodePort
  selector:
    app: kubernautics
  ports:
    - port: 3030
      targetPort: 3000
      nodePort: 30100
